# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RCquxq6vRW41R2MLyMRYyF79POX0b1RE
"""

While true:
    Try:
        n1= int(input("4"))
        break
    except ValueError:
      print("El valor introducido no es un número. Intenta de nuevo")

n1 = input("4")
n2 = input("6")
print = (n1+n2)